  services:
    postgres:
      image: postgres:13
      container_name: airflow-postgres
      restart: unless-stopped
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - postgres-db-volume:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
        interval: 10s
        timeout: 3s
        retries: 3

    redis:
      image: redis:alpine
      container_name: airflow-redis
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 5s

    init:
      build: .
      image: airflow-dbt:v1.0-dev
      container_name: airflow-init
      env_file:
        - .env
      environment:
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      volumes:
        - ./dags:${AIRFLOW_HOME}/dags:ro
        - ./dbt:${AIRFLOW_HOME}/dbt
        - ./dbt/profiles:${AIRFLOW_HOME}/dbt/profiles
        - ./entrypoint.sh:/entrypoint.sh
      entrypoint: ["/bin/bash", "/entrypoint.sh"]
      depends_on:
        postgres:
          condition: service_healthy

    webserver:
      image: airflow-dbt:v1.0-dev
      container_name: airflow-webserver
      restart: unless-stopped
      env_file:
        - .env
      user: "${AIRFLOW_UID:-50000}:0"
      environment:
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
        AIRFLOW__CORE__EXECUTOR: CeleryExecutor
        AIRFLOW__CELERY__BROKER_URL: ${REDIS_URL}/0
        AIRFLOW__CELERY__WORKER_LOG_SERVER_HOST: worker
        AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${POSTGRES_URI}
        AIRFLOW__WEBSERVER__SECRET_KEY: ${SECRET_KEY}
        DBT_PROFILES_DIR: "${AIRFLOW_HOME}/dbt/profiles"
      volumes:
        - ./dags:${AIRFLOW_HOME}/dags:ro
        - ./dbt:${AIRFLOW_HOME}/dbt
        - ./dbt/profiles:${AIRFLOW_HOME}/dbt/profiles
      ports:
        - "8080:8080"
        - "8793:8793"
      depends_on:
        redis:
          condition: service_healthy
        init:
          condition: service_completed_successfully
      command: webserver
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "5m"
    
    worker:
      image: airflow-dbt:v1.0-dev
      container_name: airflow-worker
      command: >
        /bin/bash -c "
          find /opt/airflow/dbt -type d -exec chmod 775 {} \; &&
          find /opt/airflow/dbt -type f -exec chmod 664 {} \; &&
          chown -R airflow:airflow /opt/airflow/dbt &&
          exec airflow worker"
      user: "${AIRFLOW_UID:-50000}:0"
      restart: unless-stopped
      env_file:
        - .env
      environment:
        # Required to handle warm shutdown of the celery workers properly
        # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
        DUMB_INIT_SETSID: "0"
      volumes:
        - ./dags:${AIRFLOW_HOME}/dags
        - ./dbt:${AIRFLOW_HOME}/dbt
        - ./dbt/profiles:${AIRFLOW_HOME}/dbt/profiles
      depends_on:
        webserver:
          condition: service_healthy
      healthcheck:
        # yamllint disable rule:line-length
        test:
          - "CMD-SHELL"
          - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "5m"

    scheduler:
      image: airflow-dbt:v1.0-dev
      container_name: airflow-scheduler
      restart: unless-stopped
      command: scheduler
      user: "${AIRFLOW_UID:-50000}:0"
      env_file:
        - .env
      volumes:
        - ./dags:${AIRFLOW_HOME}/dags:ro
        - ./dbt:${AIRFLOW_HOME}/dbt
        - ./dbt/profiles:${AIRFLOW_HOME}/dbt/profiles
      depends_on:
        redis:
          condition: service_healthy
        postgres:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "5m"
    
    triggerer:
      image: airflow-dbt:v1.0-dev
      container_name: airflow-triggerer
      command: triggerer
      user: "${AIRFLOW_UID:-50000}:0"
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - ./dags:${AIRFLOW_HOME}/dags:ro
        - ./dbt:${AIRFLOW_HOME}/dbt
        - ./dbt/profiles:${AIRFLOW_HOME}/dbt/profiles
      depends_on:
        scheduler:
          condition: service_healthy
      healthcheck:
        test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "5m"

    flower:
      image: mher/flower:latest
      container_name: airflow-flower
      command: celery flower
      profiles:
        - flower
      restart: unless-stopped
      env_file:
        - .env
      environment:
        CELERY_RESULT_BACKEND: ${REDIS_URL}/0
        CELERY_BROKER_URL: ${REDIS_URL}/0
      ports:
        - "5555:5555"
      depends_on:
        redis:
          condition: service_healthy
        worker:
          condition: service_healthy
        init:
          condition: service_completed_successfully
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "5m"

  volumes:
    postgres-db-volume:

