version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: launches

models:
  - name: stg_launches
    description: "Staging model for SpaceX launches, cleans and types source data."
    tags: ['staging']
    columns:
      - name: id
        description: "Primary key for the launch."
        tests:
          - not_null
      - name: name
        description: "Name of the mission."
      - name: launched_at
        description: "Datetime of the launch (UTC)."
      - name: launch_success
        description: "Boolean indicating launch success."
      - name: rocket
        description: "Rocket ID."
      - name: details
        description: "Additional mission details."
      - name: flight_number
        description: "Flight number of the launch."